version: '3'
services:
  web:
    image: python:3.8
    volumes:
      - ./:/app
    ports:
      - "8080:8080"
    working_dir: /app
    environment:
      - FLASK_ENV=production
    command: bash -c "
      pip install --upgrade pip &&
      pip install flask gunicorn flask_sqlalchemy &&
      gunicorn -b 0.0.0.0:8080 --timeout 120 server:app"
